### ISSUE TITLE
Python TURTLE not working as expected, doesn't run turtle.

### ISSUE THREAD

**Issue by YashKarthik** [d125q/atom-turtle#1]
I am running this package in atom on macOS Mojave and wished to do some turtle stuff in python, and this was the only package in there and tried running and it doesn't. Its doesn't return any errors either. The same code runs perfectly in the python IDLE but i wanna use atom so....ya. And one more thing i'm using atom-runner to run my scripts.

**Comment by d125q** [comment]
Sorry, but this repository is not for Python's `turtle` module, but for an entirely separate programming language project which we kinda never finished.
